version: '3'
services:
  app:
    image: jensendarren/nodejs_database_app
    build: .
    container_name: app
    env_file:
      - app.env
    volumes:
      - ./src:/app/src:ro
      - /app/node_modules # do not override node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run dev
    stdin_open: true
    tty: true

  db:
    image: postgres:13.3
    container_name: db
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: 123456789
  #   volumes:
  #     - ./pgadmin-servers.json:/pgadmin4/servers.json:ro

volumes:
  database-data: